// Protobuf wire schema for the NetTact agent -> server telemetry channel and its
// ack (architecture 5.1 / 15.2-3). This is the compact binary encoding offered
// alongside JSON on the /api/v1/telemetry hop; the canonical in-memory types
// remain the hand-written Go structs in protocol/telemetry and protocol/config.
//
// Field numbers follow the current struct field order and MUST NOT be reused or
// renumbered once shipped. Open string enums (kind, type, severity, layer, op)
// stay `string` on the wire so unknown values are tolerated, matching the JSON
// contract. Message-typed fields (host_snapshot, snapshot_request, desired_state)
// are optional: absence == the Go nil pointer.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: telemetry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Packet mirrors telemetry.Packet — one batched, idempotent upload.
type Packet struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion         int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	AgentId               string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SiteId                string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Sequence              uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentAt                *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Metrics               []*Metric              `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Events                []*Event               `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	InventoryDelta        []*InventoryItem       `protobuf:"bytes,8,rep,name=inventory_delta,json=inventoryDelta,proto3" json:"inventory_delta,omitempty"`
	ReportedConfigVersion int32                  `protobuf:"varint,9,opt,name=reported_config_version,json=reportedConfigVersion,proto3" json:"reported_config_version,omitempty"`
	HostSnapshot          *HostSnapshot          `protobuf:"bytes,10,opt,name=host_snapshot,json=hostSnapshot,proto3" json:"host_snapshot,omitempty"` // nil in normal packets
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Packet) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Packet) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *Packet) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Packet) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Packet) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Packet) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Packet) GetInventoryDelta() []*InventoryItem {
	if x != nil {
		return x.InventoryDelta
	}
	return nil
}

func (x *Packet) GetReportedConfigVersion() int32 {
	if x != nil {
		return x.ReportedConfigVersion
	}
	return 0
}

func (x *Packet) GetHostSnapshot() *HostSnapshot {
	if x != nil {
		return x.HostSnapshot
	}
	return nil
}

// Metric mirrors telemetry.Metric.
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // open enum (telemetry.MetricKind)
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Layer         string                 `protobuf:"bytes,4,opt,name=layer,proto3" json:"layer,omitempty"` // open enum (telemetry.HealthLayer)
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Metric) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Metric) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Metric) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Event mirrors telemetry.Event.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`         // open enum (telemetry.EventType)
	Layer         string                 `protobuf:"bytes,4,opt,name=layer,proto3" json:"layer,omitempty"`       // open enum (telemetry.HealthLayer)
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"` // open enum (telemetry.Severity)
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,7,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// InventoryItem mirrors telemetry.InventoryItem.
type InventoryItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // open enum (telemetry.InventoryKind)
	Op    string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`     // open enum (telemetry.DeltaOp)
	Id    string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// device fields
	Mac      string                 `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip       string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Vendor   string                 `protobuf:"bytes,7,opt,name=vendor,proto3" json:"vendor,omitempty"`
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// interface fields
	Name          string   `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Addrs         []string `protobuf:"bytes,10,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Gateway       string   `protobuf:"bytes,11,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Dns           []string `protobuf:"bytes,12,rep,name=dns,proto3" json:"dns,omitempty"`
	Up            bool     `protobuf:"varint,13,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *InventoryItem) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *InventoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryItem) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *InventoryItem) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InventoryItem) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *InventoryItem) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *InventoryItem) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *InventoryItem) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *InventoryItem) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *InventoryItem) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

// HostSnapshot mirrors telemetry.HostSnapshot (ephemeral, on-demand).
type HostSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProcessTotal  int32                  `protobuf:"varint,3,opt,name=process_total,json=processTotal,proto3" json:"process_total,omitempty"`
	Processes     []*ProcessInfo         `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`
	Connections   []*ConnectionInfo      `protobuf:"bytes,5,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostSnapshot) Reset() {
	*x = HostSnapshot{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSnapshot) ProtoMessage() {}

func (x *HostSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSnapshot.ProtoReflect.Descriptor instead.
func (*HostSnapshot) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *HostSnapshot) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *HostSnapshot) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HostSnapshot) GetProcessTotal() int32 {
	if x != nil {
		return x.ProcessTotal
	}
	return 0
}

func (x *HostSnapshot) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *HostSnapshot) GetConnections() []*ConnectionInfo {
	if x != nil {
		return x.Connections
	}
	return nil
}

// ProcessInfo mirrors telemetry.ProcessInfo.
type ProcessInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pid            int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User           string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CpuPct         float64                `protobuf:"fixed64,5,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	RssBytes       uint64                 `protobuf:"varint,6,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	VirtBytes      uint64                 `protobuf:"varint,7,opt,name=virt_bytes,json=virtBytes,proto3" json:"virt_bytes,omitempty"`
	DiskReadBytes  uint64                 `protobuf:"varint,8,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes uint64                 `protobuf:"varint,9,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"`
	RunTimeSeconds float64                `protobuf:"fixed64,10,opt,name=run_time_seconds,json=runTimeSeconds,proto3" json:"run_time_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessInfo) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *ProcessInfo) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *ProcessInfo) GetVirtBytes() uint64 {
	if x != nil {
		return x.VirtBytes
	}
	return 0
}

func (x *ProcessInfo) GetDiskReadBytes() uint64 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *ProcessInfo) GetDiskWriteBytes() uint64 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

func (x *ProcessInfo) GetRunTimeSeconds() float64 {
	if x != nil {
		return x.RunTimeSeconds
	}
	return 0
}

// ConnectionInfo mirrors telemetry.ConnectionInfo.
type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,2,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName   string                 `protobuf:"bytes,6,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectionInfo) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *ConnectionInfo) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *ConnectionInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ConnectionInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConnectionInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ConnectionInfo) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

// TelemetryAck is the server -> agent response on the telemetry hop. It mirrors
// server-core's telemetryResponse / agent uploader.Ack.
type TelemetryAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HighestSequence uint64                 `protobuf:"varint,1,opt,name=highest_sequence,json=highestSequence,proto3" json:"highest_sequence,omitempty"`
	ServerTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ConfigVersion   int32                  `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	DesiredState    *DesiredState          `protobuf:"bytes,4,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"` // nil unless a config downlink is attached
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetryAck) GetHighestSequence() uint64 {
	if x != nil {
		return x.HighestSequence
	}
	return 0
}

func (x *TelemetryAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *TelemetryAck) GetConfigVersion() int32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *TelemetryAck) GetDesiredState() *DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return nil
}

// DesiredState mirrors config.DesiredState (the config downlink).
type DesiredState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion   int32                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	ProbeTargets    []*ProbeTarget         `protobuf:"bytes,2,rep,name=probe_targets,json=probeTargets,proto3" json:"probe_targets,omitempty"`
	Intervals       *Intervals             `protobuf:"bytes,3,opt,name=intervals,proto3" json:"intervals,omitempty"`
	SnapshotRequest *SnapshotRequest       `protobuf:"bytes,4,opt,name=snapshot_request,json=snapshotRequest,proto3" json:"snapshot_request,omitempty"` // nil unless a live snapshot is requested
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *DesiredState) GetConfigVersion() int32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *DesiredState) GetProbeTargets() []*ProbeTarget {
	if x != nil {
		return x.ProbeTargets
	}
	return nil
}

func (x *DesiredState) GetIntervals() *Intervals {
	if x != nil {
		return x.Intervals
	}
	return nil
}

func (x *DesiredState) GetSnapshotRequest() *SnapshotRequest {
	if x != nil {
		return x.SnapshotRequest
	}
	return nil
}

// SnapshotRequest mirrors config.SnapshotRequest.
type SnapshotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WantProcesses   bool                   `protobuf:"varint,2,opt,name=want_processes,json=wantProcesses,proto3" json:"want_processes,omitempty"`
	WantConnections bool                   `protobuf:"varint,3,opt,name=want_connections,json=wantConnections,proto3" json:"want_connections,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *SnapshotRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SnapshotRequest) GetWantProcesses() bool {
	if x != nil {
		return x.WantProcesses
	}
	return false
}

func (x *SnapshotRequest) GetWantConnections() bool {
	if x != nil {
		return x.WantConnections
	}
	return false
}

// ProbeTarget mirrors config.ProbeTarget. Field 3 (tier) was removed and is
// reserved so the number/name can never be silently reused by a future field.
type ProbeTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Params        *ProbeParams           `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTarget) Reset() {
	*x = ProbeTarget{}
	mi := &file_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTarget) ProtoMessage() {}

func (x *ProbeTarget) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTarget.ProtoReflect.Descriptor instead.
func (*ProbeTarget) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *ProbeTarget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProbeTarget) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProbeTarget) GetParams() *ProbeParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ProbeTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ProbeParams mirrors config.ProbeParams (zero == collector default).
type ProbeParams struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IntervalSeconds int32                  `protobuf:"varint,1,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutMs       int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	PacketSize      int32                  `protobuf:"varint,3,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	Retries         int32                  `protobuf:"varint,4,opt,name=retries,proto3" json:"retries,omitempty"`
	RecordType      string                 `protobuf:"bytes,5,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Method          string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	ExpectedStatus  int32                  `protobuf:"varint,7,opt,name=expected_status,json=expectedStatus,proto3" json:"expected_status,omitempty"`
	// Appended fields (never renumber the above).
	Keyword          string            `protobuf:"bytes,8,opt,name=keyword,proto3" json:"keyword,omitempty"`
	KeywordInvert    bool              `protobuf:"varint,9,opt,name=keyword_invert,json=keywordInvert,proto3" json:"keyword_invert,omitempty"`
	AcceptedStatuses string            `protobuf:"bytes,10,opt,name=accepted_statuses,json=acceptedStatuses,proto3" json:"accepted_statuses,omitempty"`
	Headers          map[string]string `protobuf:"bytes,11,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body             string            `protobuf:"bytes,12,opt,name=body,proto3" json:"body,omitempty"`
	MaxRedirects     int32             `protobuf:"varint,13,opt,name=max_redirects,json=maxRedirects,proto3" json:"max_redirects,omitempty"`
	IgnoreTls        bool              `protobuf:"varint,14,opt,name=ignore_tls,json=ignoreTls,proto3" json:"ignore_tls,omitempty"`
	MaxResponseBytes int32             `protobuf:"varint,15,opt,name=max_response_bytes,json=maxResponseBytes,proto3" json:"max_response_bytes,omitempty"`
	Port             int32             `protobuf:"varint,16,opt,name=port,proto3" json:"port,omitempty"`
	Tls              bool              `protobuf:"varint,17,opt,name=tls,proto3" json:"tls,omitempty"`
	PacketCount      int32             `protobuf:"varint,18,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	GlobalTimeoutMs  int32             `protobuf:"varint,19,opt,name=global_timeout_ms,json=globalTimeoutMs,proto3" json:"global_timeout_ms,omitempty"`
	ResolverServer   string            `protobuf:"bytes,20,opt,name=resolver_server,json=resolverServer,proto3" json:"resolver_server,omitempty"`
	ResolverPort     int32             `protobuf:"varint,21,opt,name=resolver_port,json=resolverPort,proto3" json:"resolver_port,omitempty"`
	ResolverProtocol string            `protobuf:"bytes,22,opt,name=resolver_protocol,json=resolverProtocol,proto3" json:"resolver_protocol,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProbeParams) Reset() {
	*x = ProbeParams{}
	mi := &file_telemetry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeParams) ProtoMessage() {}

func (x *ProbeParams) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeParams.ProtoReflect.Descriptor instead.
func (*ProbeParams) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{11}
}

func (x *ProbeParams) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ProbeParams) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ProbeParams) GetPacketSize() int32 {
	if x != nil {
		return x.PacketSize
	}
	return 0
}

func (x *ProbeParams) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *ProbeParams) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *ProbeParams) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProbeParams) GetExpectedStatus() int32 {
	if x != nil {
		return x.ExpectedStatus
	}
	return 0
}

func (x *ProbeParams) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ProbeParams) GetKeywordInvert() bool {
	if x != nil {
		return x.KeywordInvert
	}
	return false
}

func (x *ProbeParams) GetAcceptedStatuses() string {
	if x != nil {
		return x.AcceptedStatuses
	}
	return ""
}

func (x *ProbeParams) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProbeParams) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ProbeParams) GetMaxRedirects() int32 {
	if x != nil {
		return x.MaxRedirects
	}
	return 0
}

func (x *ProbeParams) GetIgnoreTls() bool {
	if x != nil {
		return x.IgnoreTls
	}
	return false
}

func (x *ProbeParams) GetMaxResponseBytes() int32 {
	if x != nil {
		return x.MaxResponseBytes
	}
	return 0
}

func (x *ProbeParams) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProbeParams) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *ProbeParams) GetPacketCount() int32 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *ProbeParams) GetGlobalTimeoutMs() int32 {
	if x != nil {
		return x.GlobalTimeoutMs
	}
	return 0
}

func (x *ProbeParams) GetResolverServer() string {
	if x != nil {
		return x.ResolverServer
	}
	return ""
}

func (x *ProbeParams) GetResolverPort() int32 {
	if x != nil {
		return x.ResolverPort
	}
	return 0
}

func (x *ProbeParams) GetResolverProtocol() string {
	if x != nil {
		return x.ResolverProtocol
	}
	return ""
}

// Intervals mirrors config.Intervals.
type Intervals struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseSeconds    int32                  `protobuf:"varint,1,opt,name=base_seconds,json=baseSeconds,proto3" json:"base_seconds,omitempty"`
	RegularSeconds int32                  `protobuf:"varint,2,opt,name=regular_seconds,json=regularSeconds,proto3" json:"regular_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Intervals) Reset() {
	*x = Intervals{}
	mi := &file_telemetry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intervals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intervals) ProtoMessage() {}

func (x *Intervals) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intervals.ProtoReflect.Descriptor instead.
func (*Intervals) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{12}
}

func (x *Intervals) GetBaseSeconds() int32 {
	if x != nil {
		return x.BaseSeconds
	}
	return 0
}

func (x *Intervals) GetRegularSeconds() int32 {
	if x != nil {
		return x.RegularSeconds
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x0fnettact.wire.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x03\n" +
	"\x06Packet\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x121\n" +
	"\ametrics\x18\x06 \x03(\v2\x17.nettact.wire.v1.MetricR\ametrics\x12.\n" +
	"\x06events\x18\a \x03(\v2\x16.nettact.wire.v1.EventR\x06events\x12G\n" +
	"\x0finventory_delta\x18\b \x03(\v2\x1e.nettact.wire.v1.InventoryItemR\x0einventoryDelta\x126\n" +
	"\x17reported_config_version\x18\t \x01(\x05R\x15reportedConfigVersion\x12B\n" +
	"\rhost_snapshot\x18\n" +
	" \x01(\v2\x1d.nettact.wire.v1.HostSnapshotR\fhostSnapshot\"\x98\x02\n" +
	"\x06Metric\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x14\n" +
	"\x05layer\x18\x04 \x01(\tR\x05layer\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12;\n" +
	"\x06labels\x18\a \x03(\v2#.nettact.wire.v1.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05layer\x18\x04 \x01(\tR\x05layer\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x127\n" +
	"\x05attrs\x18\a \x03(\v2!.nettact.wire.v1.Event.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x02\n" +
	"\rInventoryItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x16\n" +
	"\x06vendor\x18\a \x01(\tR\x06vendor\x127\n" +
	"\tlast_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x14\n" +
	"\x05addrs\x18\n" +
	" \x03(\tR\x05addrs\x12\x18\n" +
	"\agateway\x18\v \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\f \x03(\tR\x03dns\x12\x0e\n" +
	"\x02up\x18\r \x01(\bR\x02up\"\xfd\x01\n" +
	"\fHostSnapshot\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12#\n" +
	"\rprocess_total\x18\x03 \x01(\x05R\fprocessTotal\x12:\n" +
	"\tprocesses\x18\x04 \x03(\v2\x1c.nettact.wire.v1.ProcessInfoR\tprocesses\x12A\n" +
	"\vconnections\x18\x05 \x03(\v2\x1f.nettact.wire.v1.ConnectionInfoR\vconnections\"\xb0\x02\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\acpu_pct\x18\x05 \x01(\x01R\x06cpuPct\x12\x1b\n" +
	"\trss_bytes\x18\x06 \x01(\x04R\brssBytes\x12\x1d\n" +
	"\n" +
	"virt_bytes\x18\a \x01(\x04R\tvirtBytes\x12&\n" +
	"\x0fdisk_read_bytes\x18\b \x01(\x04R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\t \x01(\x04R\x0ediskWriteBytes\x12(\n" +
	"\x10run_time_seconds\x18\n" +
	" \x01(\x01R\x0erunTimeSeconds\"\xb1\x01\n" +
	"\x0eConnectionInfo\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x02 \x01(\tR\tlocalAddr\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\x06 \x01(\tR\vprocessName\"\xe1\x01\n" +
	"\fTelemetryAck\x12)\n" +
	"\x10highest_sequence\x18\x01 \x01(\x04R\x0fhighestSequence\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x05R\rconfigVersion\x12B\n" +
	"\rdesired_state\x18\x04 \x01(\v2\x1d.nettact.wire.v1.DesiredStateR\fdesiredState\"\xff\x01\n" +
	"\fDesiredState\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x05R\rconfigVersion\x12A\n" +
	"\rprobe_targets\x18\x02 \x03(\v2\x1c.nettact.wire.v1.ProbeTargetR\fprobeTargets\x128\n" +
	"\tintervals\x18\x03 \x01(\v2\x1a.nettact.wire.v1.IntervalsR\tintervals\x12K\n" +
	"\x10snapshot_request\x18\x04 \x01(\v2 .nettact.wire.v1.SnapshotRequestR\x0fsnapshotRequest\"\x82\x01\n" +
	"\x0fSnapshotRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0ewant_processes\x18\x02 \x01(\bR\rwantProcesses\x12)\n" +
	"\x10want_connections\x18\x03 \x01(\bR\x0fwantConnections\"\x8f\x01\n" +
	"\vProbeTarget\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x124\n" +
	"\x06params\x18\x04 \x01(\v2\x1c.nettact.wire.v1.ProbeParamsR\x06params\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04nameJ\x04\b\x03\x10\x04R\x04tier\"\xd9\x06\n" +
	"\vProbeParams\x12)\n" +
	"\x10interval_seconds\x18\x01 \x01(\x05R\x0fintervalSeconds\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\x12\x1f\n" +
	"\vpacket_size\x18\x03 \x01(\x05R\n" +
	"packetSize\x12\x18\n" +
	"\aretries\x18\x04 \x01(\x05R\aretries\x12\x1f\n" +
	"\vrecord_type\x18\x05 \x01(\tR\n" +
	"recordType\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12'\n" +
	"\x0fexpected_status\x18\a \x01(\x05R\x0eexpectedStatus\x12\x18\n" +
	"\akeyword\x18\b \x01(\tR\akeyword\x12%\n" +
	"\x0ekeyword_invert\x18\t \x01(\bR\rkeywordInvert\x12+\n" +
	"\x11accepted_statuses\x18\n" +
	" \x01(\tR\x10acceptedStatuses\x12C\n" +
	"\aheaders\x18\v \x03(\v2).nettact.wire.v1.ProbeParams.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\f \x01(\tR\x04body\x12#\n" +
	"\rmax_redirects\x18\r \x01(\x05R\fmaxRedirects\x12\x1d\n" +
	"\n" +
	"ignore_tls\x18\x0e \x01(\bR\tignoreTls\x12,\n" +
	"\x12max_response_bytes\x18\x0f \x01(\x05R\x10maxResponseBytes\x12\x12\n" +
	"\x04port\x18\x10 \x01(\x05R\x04port\x12\x10\n" +
	"\x03tls\x18\x11 \x01(\bR\x03tls\x12!\n" +
	"\fpacket_count\x18\x12 \x01(\x05R\vpacketCount\x12*\n" +
	"\x11global_timeout_ms\x18\x13 \x01(\x05R\x0fglobalTimeoutMs\x12'\n" +
	"\x0fresolver_server\x18\x14 \x01(\tR\x0eresolverServer\x12#\n" +
	"\rresolver_port\x18\x15 \x01(\x05R\fresolverPort\x12+\n" +
	"\x11resolver_protocol\x18\x16 \x01(\tR\x10resolverProtocol\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\tIntervals\x12!\n" +
	"\fbase_seconds\x18\x01 \x01(\x05R\vbaseSeconds\x12'\n" +
	"\x0fregular_seconds\x18\x02 \x01(\x05R\x0eregularSecondsB(Z&github.com/nettact/protocol/wire/pb;pbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_telemetry_proto_goTypes = []any{
	(*Packet)(nil),                // 0: nettact.wire.v1.Packet
	(*Metric)(nil),                // 1: nettact.wire.v1.Metric
	(*Event)(nil),                 // 2: nettact.wire.v1.Event
	(*InventoryItem)(nil),         // 3: nettact.wire.v1.InventoryItem
	(*HostSnapshot)(nil),          // 4: nettact.wire.v1.HostSnapshot
	(*ProcessInfo)(nil),           // 5: nettact.wire.v1.ProcessInfo
	(*ConnectionInfo)(nil),        // 6: nettact.wire.v1.ConnectionInfo
	(*TelemetryAck)(nil),          // 7: nettact.wire.v1.TelemetryAck
	(*DesiredState)(nil),          // 8: nettact.wire.v1.DesiredState
	(*SnapshotRequest)(nil),       // 9: nettact.wire.v1.SnapshotRequest
	(*ProbeTarget)(nil),           // 10: nettact.wire.v1.ProbeTarget
	(*ProbeParams)(nil),           // 11: nettact.wire.v1.ProbeParams
	(*Intervals)(nil),             // 12: nettact.wire.v1.Intervals
	nil,                           // 13: nettact.wire.v1.Metric.LabelsEntry
	nil,                           // 14: nettact.wire.v1.Event.AttrsEntry
	nil,                           // 15: nettact.wire.v1.ProbeParams.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_telemetry_proto_depIdxs = []int32{
	16, // 0: nettact.wire.v1.Packet.sent_at:type_name -> google.protobuf.Timestamp
	1,  // 1: nettact.wire.v1.Packet.metrics:type_name -> nettact.wire.v1.Metric
	2,  // 2: nettact.wire.v1.Packet.events:type_name -> nettact.wire.v1.Event
	3,  // 3: nettact.wire.v1.Packet.inventory_delta:type_name -> nettact.wire.v1.InventoryItem
	4,  // 4: nettact.wire.v1.Packet.host_snapshot:type_name -> nettact.wire.v1.HostSnapshot
	16, // 5: nettact.wire.v1.Metric.ts:type_name -> google.protobuf.Timestamp
	13, // 6: nettact.wire.v1.Metric.labels:type_name -> nettact.wire.v1.Metric.LabelsEntry
	16, // 7: nettact.wire.v1.Event.ts:type_name -> google.protobuf.Timestamp
	14, // 8: nettact.wire.v1.Event.attrs:type_name -> nettact.wire.v1.Event.AttrsEntry
	16, // 9: nettact.wire.v1.InventoryItem.last_seen:type_name -> google.protobuf.Timestamp
	16, // 10: nettact.wire.v1.HostSnapshot.ts:type_name -> google.protobuf.Timestamp
	5,  // 11: nettact.wire.v1.HostSnapshot.processes:type_name -> nettact.wire.v1.ProcessInfo
	6,  // 12: nettact.wire.v1.HostSnapshot.connections:type_name -> nettact.wire.v1.ConnectionInfo
	16, // 13: nettact.wire.v1.TelemetryAck.server_time:type_name -> google.protobuf.Timestamp
	8,  // 14: nettact.wire.v1.TelemetryAck.desired_state:type_name -> nettact.wire.v1.DesiredState
	10, // 15: nettact.wire.v1.DesiredState.probe_targets:type_name -> nettact.wire.v1.ProbeTarget
	12, // 16: nettact.wire.v1.DesiredState.intervals:type_name -> nettact.wire.v1.Intervals
	9,  // 17: nettact.wire.v1.DesiredState.snapshot_request:type_name -> nettact.wire.v1.SnapshotRequest
	11, // 18: nettact.wire.v1.ProbeTarget.params:type_name -> nettact.wire.v1.ProbeParams
	15, // 19: nettact.wire.v1.ProbeParams.headers:type_name -> nettact.wire.v1.ProbeParams.HeadersEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
